#!/bin/bash

echo "Jenkins Migration Steps:"
echo "1. SSH into Jenkins server:"
echo "   ssh -i ~/.ssh/your-key.pem ubuntu@54.70.16.253"
echo ""
echo "2. Configure AWS credentials:"
echo "   aws configure"
echo "   AWS Access Key ID: [Your AWS Access Key]"
echo "   AWS Secret Access Key: [Your AWS Secret Key]"
echo "   Default region name: us-west-2"
echo ""
echo "3. Run these commands on Jenkins server:"
echo ""
echo "# Backup Jenkins"
echo "sudo systemctl stop jenkins"
echo "sudo tar -czf /tmp/jenkins_backup.tar.gz /var/lib/jenkins"
echo ""
echo "# Create network interface in EKS VPC"
echo "ENI_ID=\$(aws ec2 create-network-interface \\"
echo "    --subnet-id subnet-08c2208c1ddbc2a0e \\"
echo "    --groups sg-029b97cf66e756f53 \\"
echo "    --description 'Jenkins EKS Network Interface' \\"
echo "    --query 'NetworkInterface.NetworkInterfaceId' \\"
echo "    --output text)"
echo ""
echo "# Get instance ID"
echo "INSTANCE_ID=\$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
echo ""
echo "# Attach network interface"
echo "aws ec2 attach-network-interface \\"
echo "    --network-interface-id \$ENI_ID \\"
echo "    --instance-id \$INSTANCE_ID \\"
echo "    --device-index 1"
echo ""
echo "# Start Jenkins"
echo "sudo systemctl start jenkins"
echo ""
echo "# Verify connectivity"
echo "kubectl get nodes"
