
FROM nginx:alpine
# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*
# Copy your built files to nginx web root
COPY dist /usr/share/nginx/html
# Copy default Nginx config if you want custom behavior (optional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
